# Generated by Django 4.2.2 on 2023-06-26 09:27

from django.db import migrations


def connect_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.owner))
        owner.save()


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.update(flats=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_flat_owner_alter_owner_owner_and_more'),
    ]

    operations = [
        migrations.RunPython(connect_owners_and_flats, move_backward)
    ]
