# Generated by Django 4.2.2 on 2023-06-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0014_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='flat_complaint',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='text_complaint',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='author_login',
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался:'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='who_liked', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул:'),
        ),
    ]
