# Generated by Django 4.2.2 on 2023-06-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_flat_complaint_complaint_flat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
    ]
